[package]
name = "rwm_locals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-absolutize = "3.0.11"
serde = "1.0.133"
pager = "0.16.0"
rwm_xml = {path = "../rwm_xml"}